azure-pipelines-steps.yml
azure-pipelines.yml

This change makes it so that PRs that affect only README.md don't build anything, and changes only to that file and things in the docs directory only build the docs as part of CI (everything else will continue to run all build steps).

Enable conditional build logic depending on PR changes

---

econml/metalearners.py
econml/tests/test_metalearners.py

In this commit:
* fit method now accepts W (default=None) in DoublyRobustLearner.
outcome model and propensity model is fit on X||W.
* A new test for DoublyRobustLearner with X and W separate.
Resolves: #19

Added support for W in DoublyRobustLearner class.

---

econml/cate_estimator.py
econml/dml.py
econml/tests/test_dml.py

This set of changes makes it so that DML can work with vector T or Y, and also makes X optional to comply with the signature.

Correct DML shapes for vectors

---

econml/dml.py
econml/tests/test_dml.py

This pull request refactors the DML classes, adding an internal base class that should allow us to generalize to "3ML" a la the Orthogonal Statistical Learning paper by Dylan and Vasilis.

Refactor DML classes to use a more general RLearner base class

---

setup.cfg

Pickling local objects doesn't work in versions of joblib prior to 0.13.0, which was breaking some of our code.

Update joblib dependency to at least 0.13.0

---

setup.cfg

Matplotlib 3.1 requires Python version >= 3.6; since we don't take a hard dependency on matplotlib (we only use it in tests) we should continue to use older versions so that we can still test against Python 3.5

Pin matplotlib version to fix Python 3.5 builds

---

azure-pipelines.yml

We are currently incorrectly running all tasks as part of CI when there are only changes to the notebooks, instead of only running the notebook tests (which we'd rather do since notebook changes can't affect anything else).

Fix notebook condition in build

---

econml/deepiv.py
econml/tests/test_deepiv.py

My last changes to this file broke `effect`, but we weren't calling it anywhere so we didn't pick it up.

Fix effect

---

doc/spec/api.rst
doc/spec/estimation/dml.rst
doc/spec/estimation/forest.rst
doc/spec/motivation.rst

Notes on a couple of the changes:
- In `motivation.rst` I changed "**for increase in** sales and revenue" to "**to increase** sales and revenue", but maybe that should be "**for increased** sales and revenue"?
- In `dml.rst` I dropped `sklearn.preprocessing` from "`LogFeatures`" in a couple places, because it looks like that's a custom class, not sklearn's.

Fixed a few typos in docs

---

azure-pipelines.yml
econml/tests/test_notebooks.py

Builds have started to break on macOS; I'm trying to see if switching from 10.13 to 10.14 affects this.

Switch CI to macOS 10.14

---

econml/tests/test_bootstrap.py
econml/tests/test_two_stage_least_squares.py

#127 details some problems with one of our bootstrap tests.  This PR is a temporary measure to enable more consistent builds by simply removing the two flaky parts of the test.  The desired improvements listed in the issue will need to be handled by a separate PR at a later date.

Remove flaky part of flaky test that's affecting builds

---

azure-pipelines.yml

We should run tests regardless of whether linting succeeds; the author will need to fix both types of issues either way, but this way they don't need to run multiple builds to see all issues.

Enable tests even when linting fails

---

doc/reference.rst
doc/spec/estimation/dml.rst
econml/_ortho_learner.py
econml/_rlearner.py
econml/bootstrap.py
econml/cate_estimator.py
econml/causal_tree.py
econml/data/dgps.py
econml/deepiv.py
econml/dml.py
econml/drlearner.py
econml/inference.py
econml/metalearners.py
econml/ortho_forest.py
econml/selective_regularization.py
econml/sklearn_extensions/linear_model.py
econml/sklearn_extensions/model_selection.py
econml/two_stage_least_squares.py
econml/utilities.py

* Clean up cross references in docs (both between internal classes, as well as to external classes like numpy's `RandomState`)
* Remove explicit `object` base class in the few places we had it, since it's completely unnecessary in python 3

Clean up cross references

---

azure-pipelines.yml

We've been experiencing long delays with our CI builds, somehow involving the jobs that run on macOS; this PR is a temporary measure to see if we can mitigate the issue by using a different OS version.

Switch to macOS 10.13 to mitigate CI delays

---

econml/cate_estimator.py
econml/dml.py
econml/drlearner.py
econml/inference.py
econml/sklearn_extensions/linear_model.py
econml/tests/test_drlearner.py
econml/utilities.py

A DRLearner with a debiased lasso final model that enables inference when the heterogeneity features are high dimensional.

Added SparseLinearDRLearner

---

azure-pipelines.yml
doc/reference.rst
doc/spec/estimation/dml.rst
doc/spec/estimation/forest.rst
doc/spec/estimation/metalearners.rst
doc/spec/inference.rst
econml/_ortho_learner.py
econml/_rlearner.py
econml/cate_estimator.py
econml/dml.py
econml/drlearner.py
econml/ortho_forest.py
econml/sklearn_extensions/linear_model.py
econml/utilities.py

* We forgot to include the `sklearn_extensions` modules.
* Used a more consistent cross-reference style everywhere
* Fixed a few other miscellaneous doc issues (spelling, invalid cross refs, etc.)

Fix some documentation problems

---

setup.cfg

The new release of sklearn breaks lots of things, so I'm pinning our requirement to sklearn < 0.22 for now.

Pin sklearn < 0.22

---

README.md
econml/drlearner.py
econml/inference.py
econml/tests/test_drlearner.py
setup.cfg

As requested by the DoWhy team, this adds support for 2D arrays for the response when using DRLearner (though still limited to a single response).

Add 2d response array support to DRLearner

---

econml/drlearner.py
econml/metalearners.py
econml/tests/test_drlearner.py

Currently if `cate_models` isn't specified in the initializer, then we end up using `models` for them.  But then we fit those models before cloning them into `cate_treated_models` and `cate_controls_models`, while it would be better to clone them first, then train.

Fix XLearner issue with timing of clone

---

econml/tests/test_two_stage_least_squares.py
econml/two_stage_least_squares.py

Fix bug in marginal effect for 2SLS

---

econml/dml.py
econml/inference.py
econml/tests/test_dml.py
econml/two_stage_least_squares.py

Fix two issues

---

econml/_ortho_learner.py
econml/bootstrap.py
econml/cate_estimator.py
econml/cate_interpreter.py
econml/inference.py
econml/ortho_iv.py
econml/tests/test_bootstrap.py
econml/tests/test_dml.py
econml/tests/test_drlearner.py
econml/tests/test_inference.py
econml/tests/test_ortho_iv.py
econml/tests/test_two_stage_least_squares.py
econml/two_stage_least_squares.py
setup.cfg

Enable stratification in bootstrap

---

econml/cate_estimator.py
econml/inference.py
econml/tests/test_inference.py

Changed logic of feature names in summary_frame and added corresponding tests. Fixed a small bug in LinearModelFinalCateEstimatorDiscreteMixin where we werenot checking in intercept_ whether an intercept was fitted and raising an Attribute error if so. This lead to a weird error being raised because we were trying to reshape an integer.
Addressing #303

Changed logic in summary_frame for feature names

---

econml/_ortho_learner.py
econml/_rlearner.py
econml/dml.py
econml/drlearner.py
econml/ortho_iv.py
econml/sklearn_extensions/linear_model.py
econml/tests/test_dml.py
econml/tests/test_drlearner.py
econml/tests/test_linear_model.py
econml/utilities.py

Enabling grouping, robust linear final models.

Grouping and other changes

---

econml/inference.py
econml/tests/test_dml.py

subtracted intercept from pointwise estimate in intercetp in linear model final inference and raised extra warning. added corresponding tests that intercept is ignored.

LinearModelFinalInference was not subtracting intercept when model_final has one

---

azure-pipelines.yml
econml/_ortho_learner.py
econml/cate_estimator.py
econml/dml.py
econml/drlearner.py
econml/inference.py
econml/ortho_iv.py
econml/sklearn_extensions/linear_model.py
econml/tests/test_dml.py
econml/tests/test_drlearner.py
econml/tests/test_ortho_iv.py
econml/tests/test_statsmodels.py
econml/utilities.py

This moves `StatsModelsLinearRegression` from the `econml.utilities` package to `econml.sklearn_extensions.linear_model` package, deprecates the unused `LassoCVWrapper`, and cleans up some of our imports a bit (fixes #118).
Given that `econml.sklearn_extensions.linear_model` imports from `econml.utilities`, I couldn't find a clean way to leave a deprecated version of this class in `utilities`, but it seems unlikely that any user directly depends on this class in a way that will break.

Move StatsModelsLinearRegression

---

econml/automated_ml.py
econml/drlearner.py
econml/tests/test_automated_ml.py

Fixes #371.
Also fixes a minor drlearner issue.

Fix automl handling of positional initializer args

---

econml/tests/test_grf_python.py
econml/tree/_tree.pyx

Fixed pickling of grf tree. Fixed bug in `__setstate__` and `__getstate__`. 
(fixes #381)

fixed pickling of grf

---

azure-pipelines.yml
econml/cate_interpreter/_tree_exporter.py
econml/iv/nnet/_deepiv.py
econml/utilities.py
setup.cfg

This PR creates new `tf` and `interpret` extras, which install `tensorflow` and `keras` for `tf` and `matplotlib` and `graphviz` for `interpret`, as well as an `all` extra which installs all of those.  This allows us to remove some heavy dependencies from the main package which are only used in a very small number of places (`DeepIV` is the only place `keras` and `tensorflow` are used, and the CATE tree interpreters are the only place that `matplotlib` and `graphviz` are used).

Create new extras

---

econml/_shap.py
econml/dml/causal_forest.py
econml/dml/dml.py
econml/dr/_drlearner.py
econml/inference/_inference.py
econml/tests/test_drlearner.py
econml/tests/test_inference.py
econml/tests/test_shap.py

This PR will fix two things:
1. fix #402
2.  fix the remaining shap issue, when parse `const_marginal_effect`, original feature names is not correctly passed through

a couple of remaining small fix 

---

econml/_cate_estimator.py
econml/_shap.py
econml/dml/dml.py
econml/dr/_drlearner.py
econml/iv/dml/_dml.py
econml/iv/dr/_dr.py
econml/tests/test_integration.py
econml/utilities.py
setup.cfg

* Remove sklearn version constraint and allow for sklearn > 0.22.0 
* Make `cate_feature_names` more robust to different kinds of featurizers (fixes #421)

Fix a few 0.9.0 bugs

---

econml/_tree_exporter.py

If matplotlib is not available in the environment this import will raise an exception

Fix tree exporter utilities.MissingModule import

---

README.md
econml/__init__.py
econml/_ortho_learner.py
econml/solutions/causal_analysis/_causal_analysis.py
econml/tests/test_causal_analysis.py
setup.cfg

Addresses various minor issues.
Fixes #467.

Various causal analysis fixes

---

README.md
econml/__init__.py
econml/cate_interpreter/_interpreters.py
econml/dml/causal_forest.py
econml/inference/_inference.py
econml/policy/_forest/_tree.py
econml/solutions/causal_analysis/_causal_analysis.py
econml/tests/test_causal_analysis.py
econml/tests/test_inference.py
econml/tree/_tree_classes.py
notebooks/Solutions/Causal Interpretation for Boston Housing Price.ipynb

This makes a few changes:
* Makes `whatif` return a dataframe to harmonize with the other methods
* Supports exporting trees as dictionaries
* Removes policy treatment values; returns always treat and policy values instead
* Adds an `individualized_policy` method (and dictionary counterpart)

Improve causal analysis functionality

---

azure-pipelines.yml
econml/_tree_exporter.py
setup.cfg

Makes graphviz a soft dependency and part of the `plt` extra. Export to graphviz is not essential causal functionality.

Make graphviz a soft dependency

---

README.md
econml/__init__.py
econml/solutions/causal_analysis/_causal_analysis.py
econml/tests/test_causal_analysis.py

This PR changes three things:
* Better validation of init args of CausalAnalysis class
* Allow row-wise dictionary output for effects
* Allow preserving all levels in dataframe outputs instead of suppressing single-valued ones

Add additional causal analysis flags

---

azure-pipelines-steps.yml
azure-pipelines.yml
doc/conf.py
doc/spec/estimation/dml.rst
econml/sklearn_extensions/linear_model.py
econml/tests/test_dml.py
econml/tests/test_drlearner.py
notebooks/CustomerScenarios/Case Study - Recommendation AB Testing at An Online Travel Company - EconML + DoWhy.ipynb
setup.cfg

This PR makes a few small changes
* Reduce number of simulations in dowhy refutation to prevent notebook test timeouts
* Changes our sklearn-based linear models to remove all use of the `normalize` init arg (deprecated in sklearn 1.0, removed in sklearn 1.2)
*  Cap protobuf versions to work around tensorflow compat issue (https://github.com/protocolbuffers/protobuf/issues/10051)
*  Removes Python 3.6 support (EOL was last December and several dependencies have already dropped support)
*  Enables using Sphinx >= 5.0 for documentation generation
*  Updates the dowhy documentation links to point to their new py-why address

Several small fixes

---

notebooks/CustomerScenarios/Case Study - Using EconML to evaluate the treatment effect of training program - Lalonde dataset.ipynb

fix a typo

---

azure-pipelines-steps.yml
azure-pipelines.yml
doc/conf.py
econml/automated_ml/_automated_ml.py
econml/iv/nnet/_deepiv.py
econml/tests/test_dml.py
econml/tests/test_drlearner.py
econml/tests/test_dynamic_dml.py
econml/tests/test_two_stage_least_squares.py
econml/utilities.py

macos-10.15 will soon be deprecated in GitHub Actions and Azure Devops so we are upgrading the version of macOS that we use.
Relevant issue:
https://github.com/actions/runner-images/issues/5583
Additionally updating the deprecated ubuntu 18 image to ubuntu 20.
Fixing multiple new E275 style errors with new pycodestyle update.

update some pipeline images (macos-12, ubuntu20), fix pycodestyle E275

---

azure-pipelines.yml
econml/dowhy.py
setup.cfg

This removes dowhy as a core dependency, adding it to a new [dowhy] extra. If the user does not have dowhy installed but tries to use the DoWhyWrapper, we will give them an error message directing them to install it, and if they are using a more recent version of dowhy than our last-known-good, we'll warn them.

Remove dowhy as core dependency

---

setup.cfg

It seems that a recently released matplotlib version has broken some things for the shap library, which in turn causes some of our tests/functionality to fail.
Capping the version to avoid for now.
Relevant issues:
https://github.com/slundberg/shap/issues/2687
https://github.com/SeldonIO/alibi/issues/774

add matplotlib version ceiling

---

econml/_shap.py
econml/utilities.py

This should address the usability issue that led to #708

Avoid returning defaultdict directly

---

README.md

small update to remove the azure pipelines link from the top of our README. 
May also want to consider other updates to our README e.g. link to PyWhy, discord.

remove azure pipelines link from README

---

econml/tests/test_discrete_outcome.py

- The original code is testing the accuracy of different estimators by checking if the true Average Treatment Effect (ATE) falls within the calculated confidence interval. However, the check is done only once, using a single-point estimate (ate), which may not be sufficient to validate the estimator's performance. So it failed when the proportion of a true ATE within the confidence interval is NOT greater than 0.5 (50%).
- The new logic: To check that 50% of the values are in the 90% confidence interval (which makes sense), but it's testing this with the ate, which returns a single value, so actually the threshold isn't important, it's a single point that is either in the interval or not.  Instead, what we should do is generate W, D, and Y several times and check that most of the time the …

Fix the test_accuracy function by modifying the assertion logic

---

econml/_shap.py

This addresses the issue where the `shap_values` method in EconML did not correctly set `check_additivity=False` for shap>=0.43.0 due to a class name change from `Tree` to `TreeExplainer​`.
See #866 for details.

Fix `shap_values` compatibility with shap>=0.43.0 by adjusting `check_additivity` parameter handling for `TreeExplainer`

---

.github/workflows/ci.yml

The GitHub Actions runners updated `macos-latest` to point to `macos-14` instead of `macos-12`, but some of our dependencies have issues installing or working there because that environment runs on ARM, so we're moving back to `macos-12` explicitly for now.

Fix macos builds

---

econml/inference/_inference.py
econml/sklearn_extensions/linear_model.py

Fixing issue #878, making an optimization to NormalInferenceResults.conf_int method speed, replacing a unnecessary loop by the main usage of scipy.stats.norm.ppf function. This allows big inputs to be calculated at least 50x faster (conservative estimation).

Optimizing NormalInferenceResults confidence interval method speed

---

.github/workflows/ci.yml
README.md
econml/_version.py

The migration to the v4 version of the artifact API has somewhat broken rerunning tests for a PR in some scenarios because now artifacts are scoped to the attempt, but it's possible that we won't generate every type of artifact on every attempt (e.g. if all of our notebook tests passes in attempt 1, we won't try to run them again in attempt 2, see, e.g. https://github.com/py-why/EconML/actions/runs/8940985090/attempts/2 for a concrete example).
Unfortunately, the new merge artifact action's API doesn't provide a graceful way to handle this at the moment, so we can just set the step's `continue-on-error` property to true to ignore failures (ideally we wouldn't have to assume that this is the only reason the job can fail, but I don't see any obvious alternative).
Note that this isn't …

Work around merge failures in subsequent CI attempts

---

.github/workflows/publish-documentation.yml

In a previous change, we switched to v4 of the `upload-artifact` action but neglected to also use v4 of the `download-artifact` action, which breaks the publication workflow because the different versions are incompatible.

Fix documentation publishing workflow

---

econml/tests/test_discrete_outcome.py

Lower the frequency of ATE bounds falling into CI from 7 to 6. 
Key changes:
* [`econml/tests/test_discrete_outcome.py`](diffhunk://#diff-374e9ada5c8666b4dd2514ab93c2481efca5abfbe52ae7730aa978bb1dd37e68L64-R64): In the `test_accuracy(self)` method, the minimum required count of true ATE falling within the interval bounds has been reduced from 7 to 6.
* [`econml/tests/test_discrete_outcome.py`](diffhunk://#diff-374e9ada5c8666b4dd2514ab93c2481efca5abfbe52ae7730aa978bb1dd37e68L100-R100): Similarly, in the `test_accuracy_iv(self)` method, the minimum required count of true ATE falling within the interval bounds has been reduced from 7 to 6.2. econml.tests.test_discrete_outcome.TestDiscreteOutcome.test_accuracy_iv

Fix ATE bounds frequency

---

.github/workflows/publish-package.yml

A recent release of `cibuildwheel` has started including python 3.13, but `scipy` hasn't published any 3.13 builds yet (and building from source isn't working due to a fortran compiler issue), so building wheels on 3.13 fails.
That is fine for nightly builds, but bad for CI builds, where "last known good" should extend to versions of python as well as versions of our dependencies.  This fixes that issue by tying which versions of python are used by cibuildwheel to whether we're considering LKG status or not.

Disable Python 3.13 when building wheels for CI

---

.gitignore

Previously, .c files were generated whenever we install the environment. 
I added them to .gitignore so we don't make a mistake merging them by accident if they should be ignored.

add compiled .c files to .gitignore

---

.github/workflows/ci.yml

A breaking change to the upload-artifact GitHub Action has broken uploading coverage files (not only for us, see https://github.com/actions/upload-artifact/issues/614) and has not been reverted. This change will fix that by enabling hidden files only for those uploads.

Fix coverage upload

---

econml/inference/_inference.py
econml/tests/test_treatment_featurization.py
econml/utilities.py

Addresses the shape inconsistency in the linear DRIV implementation.  
**Changes:**
- I modified the [effect_interval](https://github.com/py-why/EconML/blob/960c0dd832943b8098d50f7b658cea49c822c31c/econml/inference/_inference.py#L284C1-L285C47) computation in LinearModelFinalInference class. This is where the inference method for LinearDRIV comes from.
- I added the modification function - reshape_outcomewise_effects - to utilities. Given an effects matrix, it reshapes the second dimension to be consistent with d_y[0]. 
**Related [issue]**(https://github.com/py-why/EconML/issues/687).  
**Testing:**
- TestDRIV --> OK
- test_inference --> OK
- test_statsmodels --> OK

"Fixes linear DRIV shape inconsistency"

---

.github/workflows/ci.yml
.github/workflows/generate_lkg.py
econml/tests/test_grf_python.py

This will generate updated LKG files and store them as an artifact as part of our nightly builds.

Add LKG generation to CI

---

econml/score/rscorer.py
econml/tests/test_rscorer.py

**Motivation:**
- To enable usage of `RScorer` class for scoring and model ensembling in the presence of discrete outcomes
**Implementation:**
- Add `discrete_outcome` attribute to `RScorer` class and pass to `LinearDML` in `RScorer.fit()` method
**File modifications:**
- `econml/score/rscorer.py` - Added `discrete_outcome` attribute
- `econml/tests/test_rscorer.py` - Added test case for discrete outcomes and CATEs that take probabilistic form

Enable Discrete Outcomes w/ RScorer

---

README.md

https://github.com/py-why/EconML/issues/932
The "Help Wanted" link in the readme is no longer working.
Current link : https://github.com/py-why/EconML?tab=readme-ov-file#help-wanted
Correct link : https://github.com/py-why/EconML?tab=readme-ov-file#finding-issues-to-help-with

Correct "Help Wanted" url in readme

---

.pre-commit-config.yaml
econml/dowhy.py
econml/tests/test_dowhy.py

1. `object` has no `__getattr__` attribute so calling `super().__getattr__` is wrong, should change it to `getattr(self, name)`.
2. `dowhy_` is not exist until `fit` is called, just have a more intuitive error message when someone calls methods without `fitting`.

fix `dowhy_` not existance issue

---

.github/workflows/generate_lkg.py
.github/workflows/publish-documentation.yml
README.md
doc/conf.py
econml/grf/_base_grftree.py
lkg-notebook.txt
lkg.txt
pyproject.toml

Fixes #938, plus cleans up some other minor issues, including enabling sklearn 1.6 and fixing our documentation builds.

Miscellaneous fixes

---

econml/solutions/causal_analysis/_causal_analysis.py

With new numpy 2.0 update the numpy.lib.function_base namespace has become private.
If you try to import it you get the error:
```
raise AttributeError(
AttributeError: numpy.lib.function_base is now private. If you are using a public function, it should be available in the main numpy namespace, otherwise check the NumPy 2.0 migration guide.
```
In econml this throws the exception:
```
/usr/share/miniconda/envs/test/lib/python3.9/site-packages/responsibleai/managers/causal_manager.py:10: in <module>
from econml.solutions.causal_analysis import CausalAnalysis
/usr/share/miniconda/envs/test/lib/python3.9/site-packages/econml/solutions/causal_analysis/__init__.py:4: in <module>
from ._causal_analysis import CausalAnalysis
/usr/share/miniconda/envs/test/lib/python3.9/site-packages/econml/solut …
```

Fix numpy iterable import in _causal_analysis.py for numpy>2.0

---

notebooks/CustomerScenarios/Case Study - Customer Segmentation at An Online Media Company - EconML + DoWhy.ipynb

Fixed two typos to make this case study more readable:
* "indentify" -> "identify"
* `sample_treatment_cast` -> `sample_treatment_costs`

Fix typos in the Customer Segmentation case study

---

econml/dml/causal_forest.py
econml/tests/test_dml.py

Issue https://github.com/py-why/EconML/issues/875
Changes:
- Fix for Causal Forest not passing `discrete_outcome` flag to RScorer. As a result, it gets initiated by it's default value `False`, which is unintended behaviour if we want `discrete_outcome=True`
- Added a test that previously failed, but now succeeds. Based on the minimal example provided [here](https://github.com/py-why/EconML/issues/875#issuecomment-2143425267)
First contribution here, please review critically for any mistakes or inconsistencies!
I see that the CI pipeline awaits approval. I think I did everything that is expected from me, so I'll mark it as ready for review. But perhaps the pipeline flags something.

Bugfix rscorer discrete outcome treatment

---

econml/_ortho_learner.py
econml/dml/_rlearner.py
econml/dml/dml.py
econml/tests/test_dml.py
econml/tests/test_ortho_learner.py

- Allow specification of an alternative sklearn score function for double ML models
- Add score_nuisances function
- All the changes to a clean branch from main, comitted with --signoff

Alternative scoring metrics - signoff on clean branch no rebase
