py-why/EconML

econml/tests/test_two_stage_least_squares.py, econml/two_stage_least_squares.py
Added controls to nonparametric 2SLS to match the spec (fixes #64).  Also made some other small improvements:
* Fixes handling of scalar treatments in `effect`
* Fixes `marginal_effect`, which was previously broken because an internal array was permuted from what was expected
=> Add controls to 2SLS

doc/spec/api.rst, doc/spec/estimation/metalearners.rst, econml/cate_estimator.py
* update doc for metalearners
* update doc for including _interval in api design
=> update doc for metalearners and api design

econml/cate_estimator.py, econml/dml.py, econml/sklearn_extensions/linear_model.py, econml/tests/test_dml.py
Removed `positive` from the list of valid attributes for the debiased lasso and multioutput debiased lasso. Made common base class LinearModelFinalCateEstimatorMixin.
=> Fixed minor debiased lasso and sparse DML bugs

econml/sklearn_extensions/linear_model.py, econml/utilities.py
=> Fixed np.diag bugs

econml/_ortho_learner.py, econml/ortho_iv.py, econml/tests/test_ortho_learner.py, setup.cfg
Fix a few small issues raised by @moprescu, plus make matplotlib requirement more flexible where possible.
=> Fix minor issues

azure-pipelines.yml, doc/spec/comparison.rst, econml/_ortho_learner.py, econml/_rlearner.py, econml/dml.py, econml/drlearner.py, econml/ortho_iv.py, econml/sklearn_extensions/ensemble.py, econml/sklearn_extensions/linear_model.py, econml/tests/test_deepiv.py, econml/tests/test_two_stage_least_squares.py, setup.cfg
Some changes to the Azure Pipelines environment, sphinx, and pycodestyle have necessitated a few changes to our build.
=> Fix build issues

notebooks/CustomerScenarios/Case Study - Customer Segmentation at An Online Media Company - EconML + DoWhy.ipynb, notebooks/CustomerScenarios/Case Study - Customer Segmentation at An Online Media Company.ipynb, notebooks/CustomerScenarios/Case Study - Multi-investment Attribution at A Software Company - EconML + DoWhy.ipynb, notebooks/CustomerScenarios/Case Study - Multi-investment Attribution at A Software Company.ipynb, notebooks/CustomerScenarios/Case Study - Recommendation AB Testing at An Online Travel Company - EconML + DoWhy.ipynb, notebooks/CustomerScenarios/Case Study - Recommendation AB Testing at An Online Travel Company.ipynb, setup.cfg
* Added multi-investment attribution customer scenario, EconML only
* Added multi-investment attribution customer scenario, EconML + DoWhy
* Updated images in the other customer scenario notebooks.
=> Added new customer scenario notebooks

README.md, doc/spec/estimation/dml.rst, econml/ortho_forest.py, econml/sklearn_extensions/ensemble.py, econml/sklearn_extensions/linear_model.py, econml/sklearn_extensions/model_selection.py, setup.cfg
This ought to fix reliance on newer sklearn versions, and also cleans up a few documentation issues.
=> Prepare bugfix release

README.md, setup.cfg
Preparing a new release, for once our outstanding PRs are accepted
=> Prepare 0.9.0b1 release

setup.cfg
=> Relax pandas version limit

README.md, econml/__init__.py
This bumps the version for the bug fix release.
=> Bump version to 0.9.1

setup.cfg
Upgrades to the current latest version of shap
=> Upgrade shap dependency

notebooks/CustomerScenarios/Case Study - Recommendation AB Testing at An Online Travel Company - EconML + DoWhy.ipynb
Description of changes: Fixing spelling on notebook 
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
=> Fixing spelling

econml/solutions/causal_analysis/_causal_analysis.py
made individualized policy return the delta from the current treatment as effect of recommendation, as compared to delta with respect to baseline. this seems more interpretable.
No other change is made. Schemas remain identical.
Also added the option for confidence intervals in the _heterogeneity_tree_output, since we want the heterogeneity tree to print the confidence intervals too, if we want to integrate it in the UI.
=> Changed the meaning of effect of treatment in individualized policy

econml/tests/test_shap.py, setup.cfg
Upgrade the econml package to include the latest version of shap, 0.40.0.
=> upgrade econml to latest version of shap

doc/spec/estimation/dr.rst
Saw some typos in the docs so thought I would do a quick PR to patch.
=> Docs - typos in dr.rst

doc/spec/motivation.rst
I was just reading through the docs to learn more and noticed a minor typo:
personalize -> personalized
=> Fix typo in motivation docs

doc/spec/api.rst
Fixed another minor typo while reading the docs
=> Another minor typo fix in docs

doc/spec/estimation/dml.rst
just a small typo found while reading docs
=> fix small typo

.github/workflows/ci.yml, .github/workflows/publish-documentation.yml, .github/workflows/publish-package.yml
We now need to use a service principal rather than a publish profile due to changes on the backend.
=> Fix authentication for website publishing

.github/workflows/publish-documentation.yml, .github/workflows/publish-package.yml, pyproject.toml
We're getting several compilation errors with Cython 3, which pinning it will work around until we're able to address them
=> Pin cython<3

doc/spec/estimation/dml.rst
Corrected a typo in dml.rst: efffect -> effect
=> Corrected a typo in dml.rst

lkg-notebook.txt, lkg.txt, pyproject.toml
=> Update supported shap versions
